GET http://localhost:8020/api/posts/pSXm6FGAXJy
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJuaWNrbmFtZSI6ImFrb3JvdmFpIiwidXNlcklkIjoiMjI2NTcyNWMtZjk1OC00YjkyLTgwY2YtODljYWM3OWE4NDZhIiwic3ViIjoiYWtvcm92YWkiLCJpYXQiOjE3MjUwMjcxNzgsImV4cCI6MTcyNTExMzU3OCwiYXV0aG9yaXRpZXMiOlsiVVNFUiJdfQ.BHLqnU4JsUkUoKbwL16kc9AJGyjwbMfL7py3r1e_xEnW94BIL69rwWwdLJKeA19S

### Create Post
POST http://localhost:8020/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJuaWNrbmFtZSI6ImFrb3JvdmFpIiwidXNlcklkIjoiMjI2NTcyNWMtZjk1OC00YjkyLTgwY2YtODljYWM3OWE4NDZhIiwic3ViIjoiYWtvcm92YWkiLCJpYXQiOjE3MjUwMjcxNzgsImV4cCI6MTcyNTExMzU3OCwiYXV0aG9yaXRpZXMiOlsiVVNFUiJdfQ.BHLqnU4JsUkUoKbwL16kc9AJGyjwbMfL7py3r1e_xEnW94BIL69rwWwdLJKeA19S

{
  "title": "Title",
  "content": "Content",
  "language": "en",
  "expiresAt": "2024-08-31T23:59:59",
  "isPublic": true
}

