eureka:
  instance:
    hostname: localhost  # Ustawia nazwę hosta instancji Eureka na "localhost"
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka  # Adres URL serwera Eureka, do którego klient się łączy (serwer Eureka działa na localhost:8761)

name:
  value: pastebin  # Nazwa usługi/aplikacji ustawiona na "akorovai"

spring:
  cloud:
    config:
      override-system-properties: false  # Wyłącza nadpisywanie zmiennych systemowych przez konfigurację z Spring Cloud Config
