server:
  port: 8030

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/posts
    username: akorovai
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    databasePlatform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baselineOnMigrate: true
    enabled: true
    baselineDescription: "init"
    baselineVersion: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    locations: classpath:db/migration
  redis:
    host: localhost
    port: 7777
  kafka:
    bootstrap-servers: localhost:9092
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.springframework.kafka.support.serializer.StringSerializer

kafka:
  topicName: delete-posts-topic

io:
  reflectoring:
    aws:
      s3:
        bucket-name: pastebin_posts

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  config:
    post-url: http://localhost:8020/api/posts