server:
  port: 8020

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  config:
    hash-generator-url: http://localhost:8030/api/posts
logging:
  level:
    software.amazon.awssdk: DEBUG
spring:
  redis:
    host: localhost
    port: 5555
  kafka:
    consumer:
      bootstrapServer: localhost:9092
      group-id: postGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: '*'
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      s3:
        region: ${AWS_REGION}

kafka:
  topicName: delete-posts-topic

io:
  reflectoring:
    aws:
      s3:
        bucketName: pastebin-posts

springdoc:
  swagger-ui:
    path: /api-docs