server:
  port: 8020

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  config:
    hash-generator-url: http://localhost:8030/api/posts
logging:
  level:
    software.amazon.awssdk: DEBUG
spring:
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      s3:
        region: ${AWS_REGION}

io:
  reflectoring:
    aws:
      s3:
        bucketName: pastebin-posts

springdoc:
  swagger-ui:
    path: /api-docs